### ISSUE TITLE
Please add me as a collaborator. 

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/dev-aug-2016#2]
Hello!

**Comment by mjanikas** [comment]
please add me too

**Comment by mfrith** [comment]
Howdy

**Comment by ghost** [comment]
Me too

**Comment by LLLRRRBBB** [comment]
Please add me as a collaborator

**Comment by asunshinehill** [comment]
me too!

**Comment by marpobuda** [comment]
Hey there!

**Comment by j-dacosta** [comment]
me too

**Comment by KevinButlerEsri** [comment]
please add.

**Comment by YuanZeng** [comment]
Please add me

**Comment by jero5765** [comment]
mee too

**Comment by ghost** [comment]
Please add me as a collaborator.

**Comment by caroso** [comment]
Hello

**Comment by WilburHughes** [comment]
class github

**Comment by githubteacher** [comment]
:tada: @mjanikas, @mfrith, @codergrl, @LLLRRRBBB, @asunshinehill, @marpobuda, @j-dacosta, @KevinButlerEsri, @YuanZeng, @jero5765, @garimadhakal, @caroso, and @WilburHughes are now  repository collaborators. :balloon:

**Comment by yuagao** [comment]
me too

**Comment by johannhj** [comment]
well, well, well......

**Comment by WilburHughes** [comment]
comment here

**Comment by ghost** [comment]
+1

**Comment by tingleeGIS** [comment]
```
   .
```

**Comment by redlands** [comment]
me too

**Comment by githubteacher** [comment]
:tada: @yuagao, @johannhj, @ez4gis, @tingleeGIS, and @redlands are now  repository collaborators. :balloon:

**Comment by silpagadi** [comment]
me too

**Comment by githubteacher** [comment]
:tada: @silpagadi is now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
@githubteacher you really need more emails!

**Comment by jero5765** [comment]
hello @mjanikas
